#!/bin/bash

echo "======================================================================"
echo "🚀 COMPLETE NEO DEPLOYMENT GUIDE"
echo "======================================================================"

echo ""
echo "✅ PHASE 1: SETUP (You are here)"
echo "   Files ready:"
echo "   • volatility_oracle.py (smart contract)"
echo "   • agentspoons_wallet.json (your wallet)"
echo "   • wallet_address.txt (your address)"

echo ""
echo "📍 PHASE 2: GET TESTNET TOKENS"
echo "   1. Open: https://neowish.ngd.network/"
echo "   2. Paste address from wallet_address.txt"
echo "   3. Request NEO and GAS"
echo "   4. Run: python check_balance.py"
echo "   5. Verify you have ~10 NEO and ~50 GAS"

echo ""
echo "🔨 PHASE 3: COMPILE CONTRACT"  
echo "   Run: neo3-boa compile volatility_oracle.py"
echo "   Files created:"
echo "   • volatility_oracle.nef"
echo "   • volatility_oracle.manifest.json"

echo ""
echo "🚀 PHASE 4: DEPLOY (Choose ONE method)"
echo ""
echo "   METHOD A: NeoCompiler (EASIEST)"
echo "   1. Visit: https://neo3.testnet.neocompiler.io/"
echo "   2. Upload .nef and .manifest files"
echo "   3. Install NeoLine wallet extension"
echo "   4. Import your private key"
echo "   5. Deploy and get CONTRACT HASH"

echo ""
echo "   METHOD B: Neo-Express (Local testing)"
echo "   1. npm install -g @neo-one/cli"
echo "   2. neo-express create"
echo "   3. neo-express contract deploy volatility_oracle.nef"

echo ""
echo "✅ PHASE 5: VERIFY DEPLOYMENT"
echo "   1. Visit: https://testnet.neotube.io/"
echo "   2. Search your contract hash"
echo "   3. See methods and transactions"
echo "   4. Take screenshots!"

echo ""
echo "📸 PHASE 6: GENERATE PROOF"
echo "   1. Fill in CONTRACT_HASH in interact_with_contract.py"
echo "   2. Run: python interact_with_contract.py"
echo "   3. Update NEO_DEPLOYMENT_PROOF.json with real values"
echo "   4. Take all required screenshots"

echo ""
echo "🏆 PHASE 7: PRESENT TO JUDGES"
echo "   Show:"
echo "   • Smart contract code"
echo "   • Deployed contract on explorer"
echo "   • Live contract interaction"
echo "   • Proof JSON file"

echo ""
echo "======================================================================"
echo "💡 IMPORTANT: Save your CONTRACT HASH after deployment!"
echo "======================================================================"
