#!/bin/bash

echo "🎥 DEMO VIDEO CREATION GUIDE"
echo "======================================================================"
echo ""
echo "✅ Video script created: video_script.md"
echo ""
echo "📹 RECORDING SETUP:"
echo ""
echo "1. Software (all free):"
echo "   • OBS Studio - Screen recording"
echo "   • Audacity - Audio editing"
echo "   • DaVinci Resolve - Video editing"
echo ""
echo "2. Before Recording:"
echo "   • Close unnecessary apps"
echo "   • Clean up desktop/browser"
echo "   • Prepare demo windows:"
echo "     - Dashboard running with live updates"
echo "     - NeoTube explorer with your contract"
echo "     - Code editor with smart contract"
echo "     - Terminal ready for demos"
echo ""
echo "3. Recording Tips:"
echo "   • Practice script 2-3 times"
echo "   • Record audio separately (better quality)"
echo "   • Keep energy high but natural"
echo "   • Show REAL working demo, not slides"
echo "   • Use smooth mouse movements"
echo "   • Pause between sections (easier editing)"
echo ""
echo "4. What to Record:"
echo "   [0:00-0:20] Problem/Hook"
echo "   [0:20-0:40] Solution intro"
echo "   [0:40-1:40] Live dashboard demo"
echo "   [1:40-2:20] Neo integration"
echo "   [2:20-2:50] Technical details"
echo "   [2:50-3:00] Close with contact"
echo ""
echo "5. Editing:"
echo "   • Cut pauses > 2 seconds"
echo "   • Add subtle background music"
echo "   • Highlight key numbers/features"
echo "   • Add captions for key terms"
echo "   • Export: 1080p, H.264, MP4"
echo ""
echo "6. Upload:"
echo "   • YouTube as 'Unlisted'"
echo "   • Title: AgentSpoons - Decentralized Volatility Oracle on Neo N3"
echo "   • Description: Link to GitHub repo"
echo "   • Include link in hackathon submission"
echo ""
echo "======================================================================"
echo "📝 Full script with timing in: video_script.md"
echo "🎬 Total target length: 3 minutes"
echo "======================================================================"
